version: 2

sources:
  - name: tickit
    description: "Redshift Sample Database"
    tags: ["tickit"]
    schema: raw_data
    database: prod
    tables:
      - name: category
      - name: date
      - name: event
      - name: listing
      - name: sales
      - name: users
      - name: venue
