data_analytics:
  outputs:
    ci:
      dbname: prod
      host: "{{ env_var('REDSHIFT_URL') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: 5439
      schema: dbt_ci_github_run
      threads: 4
      type: redshift
      user: "{{ env_var('REDSHIFT_USER') }}"
