data_analytics:
  outputs:
    ci:
      dbname: "{{ env_var('REDSHIFT_DATABASE') }}"
      host: "{{ env_var('REDSHIFT_URL') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: "{{ env_var('REDSHIFT_PORT') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      threads: 4
      type: redshift
      user: "{{ env_var('REDSHIFT_USER') }}"
